name: Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rspec:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Download CodeClimate reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop app lib config

      - name: Run RSpec
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SIMPLECOV: '1'
        run: bundle exec rspec

      - name: Report coverage to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: ./cc-test-reporter after-build -t simplecov
